### ISSUE TITLE
Incorrect entity names displayed for MSSQL RDS instances via On Host integration

### ISSUE THREAD

**Issue by myasin22** [newrelic/nri-mssql#114]
Incorrect entity names displayed for MSSQL RDS instances via On Host integration

## Description
Entity names of MSSQL RDS instances displayed in NR UI are different from the actual instance names.

## Expected Behavior
Display the correct names of MSSQL RDS instances as configured 

## On Host integration config file
- name: nri-mssql
  env:
    HOSTNAME: dev-ephesoft-db.cwkirvnl2kse.us-west-2.rds.amazonaws.com
    USERNAME: <username>
    PASSWORD: <password>
    PORT: <port>
    ENABLE_SSL: False
    TRUST_SERVER_CERTIFICATE: True
    TIMEOUT: 0

## Log

time="2023-04-14T17:22:55Z" level=debug msg="Received payload." component=integrations.emitter.Emitter env="map[ENABLE_BUFFER_METRICS:true ENABLE_DATABASE_RESERVE_METRICS:true ENABLE_SSL:False HOSTNAME:**dev-ephesoft-db.cwkirvnl2kse.us-west-2.rds.amazonaws.com** NRI_CONFIG_INTERVAL:15s PASSWORD:<HIDDEN> PORT:<REMOVED>TIMEOUT:0 TRUST_SERVER_CERTIFICATE:<HIDDEN> USERNAME:<REMOVED>]" integration_name=nri-mssql
time="2023-04-14T17:22:55Z" level=debug msg="Integration instances finished their execution. Waiting until next interval." component=integrations.runner.Runner env=production integration_name=nri-mssql role=mssql runner_uid=52cbaea0b9
time="2023-04-14T17:22:55Z" level=debug msg="Sending events to metrics-ingest." component=MetricsIngestSender **id="ms-instance:EC2AMAZ-5523GER:instance=ec2amaz-5523ger"** numEvents=120 postCount=93720 timestamps="[2023-04-14 17:22:55 +0000 GMT]"
time="2023-04-14T17:22:55Z" level=debug msg="Sending events to metrics-ingest." component=MetricsIngestSender id="ms-database:dev_ephesoft_tax_export_db:database=dev_ephesoft_tax_export_db:instance=ec2amaz-5523ger" numEvents=1 postCount=93720 timestamps="[2023-04-14 17:22:55 +0000 GMT]"
time="2023-04-14T17:22:55Z" level=debug msg="Sending events to metrics-ingest." component=MetricsIngestSender id="ms-database:Ephesoft_App_db:database=ephesoft_app_db:instance=ec2amaz-5523ger" numEvents=1 postCount=93720 timestamps="[2023-04-14 17:22:55 +0000 GMT]"
time="2023-04-14T17:22:55Z" level=debug msg="Sending events to metrics-ingest." component=MetricsIngestSender id="ms-database:Ephesoft_OM:database=ephesoft_om:instance=ec2amaz-5523ger" numEvents=1 postCount=93720 timestamps="[2023-04-14 17:22:55 +0000 GMT]"
time="2023-04-14T17:22:55Z" level=debug msg="Sending events to metrics-ingest." component=MetricsIngestSender id="ms-database:Ephesoft_Report_Archive_db:database=ephesoft_report_archive_db:instance=ec2amaz-5523ger" numEvents=1 postCount=93720 timestamps="[2023-04-14 17:22:55 +0000 GMT]"
time="2023-04-14T17:22:55Z" level=debug msg="Sending events to metrics-ingest." component=MetricsIngestSender id="ms-database:Ephesoft_Report_db:database=ephesoft_report_db:instance=ec2amaz-5523ger" numEvents=1 postCount=93720 timestamps="[2023-04-14 17:22:55 +0000 GMT]"
time="2023-04-14T17:22:55Z" level=debug msg="Sending events to metrics-ingest." component=MetricsIngestSender id="ms-database:Eway:database=eway:instance=ec2amaz-5523ger" numEvents=1 postCount=93720 timestamps="[2023-04-14 17:22:55 +0000 GMT]"

## Screenshot of entity in NR UI

![image](https://user-images.githubusercontent.com/116164496/232132386-a04855b1-d7b8-4985-924c-00e21a35f99c.png)

The expected instance name **dev-ephesoft-db** but the displayed value is **ec2amaz-5523ger**

## Permalink to entity

https://onenr.io/00jlpOvdBjW

**Comment by gsanchezgavier** [comment]
Hi ,

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs.

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!

**Comment by myasin22** [comment]
Case #00107696 has been raised for the same
