### ISSUE TITLE
Reporting MSSQL Jobs

### ISSUE THREAD

**Issue by edaniele** [newrelic/nri-mssql#38]
##### Feature Request

Feature Request

Would it be possible to add code to report on individual MSSQL Jobs? 
Similar to what is found here:  
https://www.mssqltips.com/sqlservertip/4921/queries-to-inventory-your-sql-server-agent-jobs/ 

Thanks in advance

**Comment by camdencheek** [comment]
Hi @edaniele  -- What information would be useful to you about the MSSQL jobs?

**Comment by edaniele** [comment]
OK let me confirm with the Customer.

Thanks

*Manny Daniele*
Senior Solutions Consultant
edaniele@newrelic.com
(m) 650-703-2618

**Comment by edaniele** [comment]
Camden
The Customer wants to be able to check the status of the SQL jobs on their
Production servers: which ones failed , when (possibly why) and get a
notification or indication in the dashboards.  Is this possible?

Thanks in advance

*Manny Daniele*
Senior Solutions Consultant
edaniele@newrelic.com
(m) 650-703-2618

**Comment by DavidSantia** [comment]
The latest code (version 2.3.0) allows you to add custom queries.  This will enable you to add metrics for those tables.  See https://github.com/newrelic/nri-mssql/blob/master/README.md#custom-queries

**Comment by edaniele** [comment]
Thanks so much David, this is great.

*Manny Daniele*
Senior Solutions Consultant
edaniele@newrelic.com
(m) 650-703-2618
