### ISSUE TITLE
Problems with MSSQL System Queries

### ISSUE THREAD

**Issue by tywilson44** [newrelic/nri-mssql#44]
I have a problem with the executable nri-mssql in that I need a change to be applied to the system queries this integration runs and when I rebuild the project to create the new exe, I am experiencing a problem with an error message when the integration runs:

This is the error message:

time="2020-07-31T14:50:38+02:00" level=error msg="Integration command failed" error="exit status 1" instance= integration=com.newrelic.mssql prefix=config/mssql stderr="[ERR] Error creating connection to SQL Server: InitialBytes InitializeSecurityContext failed 8009030c\n" working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-integrations"
time="2020-07-31T14:50:38+02:00" level=info msg="Integration health check finished with some errors" instance= integration=com.newrelic.mssql prefix=config/mssql working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-integrations"
time="2020-07-31T14:50:39+02:00" level=error msg="Integration command failed" error="exit status 1" instance= integration=com.newrelic.mssql prefix=config/mssql stderr="[ERR] Error creating connection to SQL Server: InitialBytes InitializeSecurityContext failed 8009030c\n" working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-integrations"

New Relic support are not engaged because this is a change to the original source.

This form is for `nri-mysql` bug reports and feature requests only.
This is NOT a help site. Do not ask help questions here.
If you need help, please use [newrelic support](http://support.newrelic.com/).

This is the change I need applied in the instance.sql query:
Current query:

select
MAX(sys_mem.total_physical_memory_kb * 1024.0) AS total_physical_memory,
MAX(sys_mem.available_physical_memory_kb * 1024.0) AS available_physical_memory,
(Max(proc_mem.physical_memory_in_use_kb) / (Max(sys_mem.total_physical_memory_kb) * 1.0)) * 100 as memory_utilization
FROM sys.dm_os_process_memory proc_mem,
    sys.dm_os_sys_memory sys_mem,
    sys.dm_os_performance_counters perf_count WHERE object_name = 'SQLServer:Memory Manager'

Required query:

select
MAX(sys_mem.total_physical_memory_kb * 1024.0) AS total_physical_memory,
MAX(sys_mem.available_physical_memory_kb * 1024.0) AS available_physical_memory,
(Max(proc_mem.physical_memory_in_use_kb) / (Max(sys_mem.total_physical_memory_kb) * 1.0)) * 100 as memory_utilization
FROM sys.dm_os_process_memory proc_mem,
    sys.dm_os_sys_memory sys_mem,
    sys.dm_os_performance_counters perf_count WHERE object_name like '%Memory Manager%'

And the a new rebuild of the executable.

**Comment by camdencheek** [comment]
Hi @tywilson44 -- just confirming, the only change you made was modifying that query?

**Comment by tywilson44** [comment]
Hi @camdencheek Yes I can confirm the only thing I needed to change was the bottom query in the instance.sql file. This line is the one I needed to change:

sys.dm_os_performance_counters perf_count WHERE object_name like '%Memory Manager%'

I needed the change because this criteria does not allow for the way my customer has named their instances.

**Comment by camdencheek** [comment]
I can't think of any reason that changing that query would cause that error. Just as a sanity check, have you tried building from master and running that against your instance?

**Comment by tywilson44** [comment]
Hi Camden,

We drew down from the master, change dthe code and tried to build on
different Windows OS. It's Just when we try to run the exe it causes a
problem.

Thanks and Regards

*Ty Wilson*

Principal Solution Consultant
+44 (0) 7825835020
twilson@newrelic.com

**Comment by carlossscastro** [comment]
Closing this issue as resolved
