### ISSUE TITLE
mssql-custom-query.yml cannot include inline comments in SQL query

### ISSUE THREAD

**Issue by dickiebowuk** [newrelic/nri-mssql#77]
Used one of your examples and anything after the inline comments was not included in the SQL query of a multi-line statement.

## Description
I have been testing the multiple custom queries solution and used two queries. The second of which is from the examples file where I select the top 15 longest running queries. On line 168 of mssql-custom-query.yml.sample file you include an inline SQL comment to say that you are filtering out the custom query statement. Anything after this comment is ignored in the query as I added an additional clause to limit the results to a single database. My statement was as follows:

```
SELECT TOP 15
        @@SERVERNAME AS [sql_hostname],
        ISNULL(DB_NAME(t.dbid),'') AS [database_name],
        LEFT(t.[text], 50) AS [short_text], 
        qs.execution_count AS [execution_count],
        qs.total_worker_time AS [cpu_time_total_ms],
        qs.total_worker_time/qs.execution_count AS [cpu_time_avg_ms],     
        qs.total_physical_reads AS [physical_reads_total],
        qs.total_physical_reads/qs.execution_count AS [physical_reads_avg],
        qs.total_logical_reads AS [logical_reads_total],
        qs.total_logical_reads/qs.execution_count AS [logical_reads_avg],
        qs.total_logical_writes AS [logical_writes_total],
        qs.total_logical_writes/qs.execution_count AS [logical_writes_avg],
        qs.total_elapsed_time AS [duration_total_ms],
        qs.total_elapsed_time/qs.execution_count AS [duration_avg_ms],
        qs.creation_time AS [creation_time],
        t.[text] AS [complete_text]
      FROM sys.dm_exec_query_stats AS qs WITH (NOLOCK)
      CROSS APPLY sys.dm_exec_sql_text(plan_handle) AS t
      WHERE t.[text] NOT LIKE '%SELECT TOP 15%qs.execution_count%'        --Ignore this query
      AND ISNULL(DB_NAME(t.dbid),'') = 'MyDatabase' 
      ORDER BY qs.total_elapsed_time/qs.execution_count DESC 
      OPTION (RECOMPILE);
```

I captured the statement being used by the agent via SQL Profiler and this was the result. 

```
SELECT TOP 15
  @@SERVERNAME AS [sql_hostname],
  ISNULL(DB_NAME(t.dbid),'') AS [database_name],
  LEFT(t.[text], 50) AS [short_text], 
  qs.execution_count AS [execution_count],
  qs.total_worker_time AS [cpu_time_total_ms],
  qs.total_worker_time/qs.execution_count AS [cpu_time_avg_ms],     
  qs.total_physical_reads AS [physical_reads_total],
  qs.total_physical_reads/qs.execution_count AS [physical_reads_avg],
  qs.total_logical_reads AS [logical_reads_total],
  qs.total_logical_reads/qs.execution_count AS [logical_reads_avg],
  qs.total_logical_writes AS [logical_writes_total],
  qs.total_logical_writes/qs.execution_count AS [logical_writes_avg],
  qs.total_elapsed_time AS [duration_total_ms],
  qs.total_elapsed_time/qs.execution_count AS [duration_avg_ms],
  qs.creation_time AS [creation_time],
  t.[text] AS [complete_text]
FROM sys.dm_exec_query_stats AS qs WITH (NOLOCK) CROSS APPLY sys.dm_exec_sql_text(plan_handle) AS t WHERE t.[text] NOT LIKE '%SELECT TOP 15%qs.execution_count%'
```

As you can see everything after the inline comment of  "--Ignore this query" has been excluded including the order by and option to recompile.

## Expected Behavior
I would have expected to see the entire custom statement being sent to SQL Server. Removing the comment resolved the issue, but as it's in the example file it is misleading.

## Steps to Reproduce
1. Include the custom query above including the comment in your mssql-custom-query.yml file and restart the agent.
2. Open a SQL Profiler trace and include SQL:StatementCompleted and look at the statements generated by the nri-mssql agent and you will see any SQL that appears on a line after the inline comment will have been excluded.

## Your Environment
Windows Server 2016 Standard
SQL Server 2019

**Comment by roobre** [comment]
Hi @dickiebowuk,
Thanks for reporting this.

I believe this is in fact a quick of the YAML config format. In our example, we use the folded style block scalar, `>`, as opposed to the literal style, signaled by `|`. This tells yaml parsers to replace all newlines within the block with spaces. As you can surely imagine, when a `-- comment` is introduced but the newline is replaced by a space, everything after the comment will be considered part of it and you will get the result you are expecting.

I suggest to replace the folding style with the literal style, such as:

```yaml
  - query: |-
      SELECT
        @@SERVERNAME AS [sql_hostname],
        SUM(deqs.total_logical_reads) AS [total_page_reads],
        SUM(deqs.total_logical_writes) AS [total_page_writes],
        CASE
          WHEN DB_NAME(dest.dbid) IS NULL THEN 'TechOps'
          ELSE DB_NAME(dest.dbid) 
        END AS [database_name]
      FROM sys.dm_exec_query_stats deqs
      CROSS APPLY sys.dm_exec_sql_text(deqs.sql_handle) AS dest
      GROUP BY DB_NAME(dest.dbid);
    database: master
    prefix: busiestDatabases_
```

This will preserve the newlines and should fix the issue you are facing.

**Comment by roobre** [comment]
I'll close this for now since it does not seem related to the integration itself, but by all means feel free to reopen if the issue persists.

**Comment by dickiebowuk** [comment]
I have just swapped to the literal style, restarted the agent and captured the sql in profiler and it has worked. So the folding style is definitely the cause. 

I copied the 'folding' style example from the sample file included with the project. I sample file needs updating. I'm not a contributor on the project.
