### ISSUE TITLE
Document which metrics will be discard when buffers metrics and reserve metrics are disabled

### ISSUE THREAD

**Issue by carlossscastro** [newrelic/nri-mssql#80]
We should improve our documentation to state which metrics are lost when users set 

`ENABLE_BUFFER_METRICS: false`

or 

`ENABLE_DATABASE_RESERVE_METRICS: false`

to be more clear on the tradeoff for improved performance.

**Comment by alaiavee** [comment]
I just responded to a customer asking for these details in a support case. Adding notes here for whomever writes up the documentation changes.

The **ENABLE_BUFFER_METRICS** argument appears to affect the database and instance buffer size metrics:

> MssqlDatabaseSample > bufferpool.sizePerDatabaseInBytes
> MssqlInstanceSample > bufferpool.sizeInBytes


As for the **ENABLE_DATABASE_RESERVE_METRICS** argument, it appears to enable or disable the following database metrics:

> MssqlDatabaseSample > pageFileTotal
> MssqlDatabaseSample > pageFileAvailable

---

**_Code References:_**

If _EnableBufferMetrics_ argument is true, it will perform the following:
- appends _instanceBufferDefinitions_ to _collectionList_ ([LINK](https://github.com/newrelic/nri-mssql/blob/03dd1665aef9f2db0f35d6d7d5c1455563006936/src/metrics/metrics.go#L39))
- calls the _processDBBufferDefinitions_ function ([LINK](https://github.com/newrelic/nri-mssql/blob/03dd1665aef9f2db0f35d6d7d5c1455563006936/src/metrics/metrics.go#L282))

[_instanceBufferDefinitions_ metric query is defined HERE](https://github.com/newrelic/nri-mssql/blob/345732e16b5ac2febeb1f0042d0a534a05d9c61c/src/metrics/instance_metric_definitions.go#L152)
Results are saved to the following metric format:
`db:"instance_buffer_pool_size" metric_name:"bufferpool.sizeInBytes" source_type:"gauge"`

[function _processDBBufferDefinitions_ defined HERE](https://github.com/newrelic/nri-mssql/blob/03dd1665aef9f2db0f35d6d7d5c1455563006936/src/metrics/metrics.go#L302)
References a call to only one query, _databaseBufferDefinitions_.

[_databaseBufferDefinitions_ query defined HERE](https://github.com/newrelic/nri-mssql/blob/e583faf1a56a69f382750c4a2d2926897f901430/src/metrics/database_metric_definitions.go#L54)
Results are saved in the following metric format:
`db:"buffer_pool_size" metric_name:"bufferpool.sizePerDatabaseInBytes" source_type:"gauge"`

**Comment by carlossscastro** [comment]
Thanks @alaiavee 

We'll update the documentation shortly.
