### ISSUE TITLE
Long Running Query - Buffer Collection

### ISSUE THREAD

**Issue by ahill-itim** [newrelic/nri-mssql#82]
Hi,

We have been noticing buffer data queries taking nearly 2 minutes to complete with this query in the nri-mssql integration:

SELECT   DB_NAME(database_id) AS db_name,   COUNT_BIG(*) * (8*1024) AS buffer_pool_size   
FROM sys.dm_os_buffer_descriptors WITH (NOLOCK)   WHERE database_id <> 32767 
AND DB_NAME(database_id) NOT IN ('master', 'tempdb', 'msdb', 'model', 'rdsadmin', 'distribution', 'model_msdb', 'model_replicatedmaster')   
GROUP BY database_id

However, if we change the query we can make a huge performance impact:

SELECT DB_NAME(database_id) as 'db_name', buffer_pool_size* (8*1024) as 'buffer_pool_size' 
FROM (
SELECT database_id, COUNT_BIG(*)  AS buffer_pool_size   
FROM sys.dm_os_buffer_descriptors a WITH (NOLOCK)   
INNER JOIN sys.sysdatabases b  WITH (NOLOCK) ON
b.dbid=a.database_id
WHERE b.dbid in 
(
SELECT dbid from sys.sysdatabases WHERE name NOT IN ('master', 'tempdb', 'msdb', 'model', 'rdsadmin', 'distribution', 'model_msdb', 'model_replicatedmaster')  
UNION ALL
SELECT 32767 
)
GROUP BY database_id
) a

a trace shows the big difference in CPU (95% less), and Duration (80% less).

Would it be possible to investigate the performance impact of the query running in the default install of nri-mssql and amend accordingly?

**Comment by paologallinaharbur** [comment]
Hello, thanks for raising this issue, it has been accepted and it is going to be prioritized.

In the meanwhile, have you tried already, as a workaround, to disable buffer metrics leveraging `EnableBufferMetrics` adding then your proposed query as a custom one?
