### ISSUE TITLE
Add debug information when custom queries return empty result set.

### ISSUE THREAD

**Issue by carlossscastro** [newrelic/nri-mssql#85]
When running custom queries we debug log errors that might be reported from running a query but we do not log anything when the query returns an empty result.
We should add such logging information to facilitate troubleshooting when no data is visible in NRDB but no errors are reported either.

Something along the lines "Query X returned 0 results"

https://github.com/newrelic/nri-mssql/blob/master/src/metrics/metrics.go#L140-L156

**Comment by sigilioso** [comment]
I'm closing this one because @marcsanmi already addressed it on #91
