### ISSUE TITLE
MSSQL Integration - nri-mssql.exe not present in the expected directory when the agent is installed. Should work out of the box as documented in the examples in the integration documentation

### ISSUE THREAD

**Issue by sajidinsaf** [newrelic/nri-mssql#86]
[NOTE]: # The MSSQL integration appears to be looking for the nri-mssql executable in the wrong folder

## Description
[NOTE]: # The Mssql integration was installed via the ms installer using default options. A CUSTOM_METRICS_QUERY was written to extract custom data.
[TIP]:  # 

## Expected Behavior
[NOTE]: # The MSSQL integration should have worked out of the box. 

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # 
time="2022-02-21T15:52:13+02:00" level=debug msg="Integration name not found. Trying another folder, if any." component=integrations.Executables folder="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations" forName=mssql-server
time="2022-02-21T15:52:13+02:00" level=debug msg="Error looking for integration executables in folder. Trying another folder, if any." component=integrations.Executables error="open C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations\\bin: The system cannot find the file specified." folder="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations\\bin" forName=mssql-server
time="2022-02-21T15:52:13+02:00" level=debug msg="Integration name not found. Trying another folder, if any." component=integrations.Executables folder="C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-integrations" forName=mssql-server
time="2022-02-21T15:52:13+02:00" level=debug msg="Integration name not found. Trying another folder, if any." component=integrations.Executables folder="C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-integrations\\bin" forName=mssql-server
time="2022-02-21T15:52:13+02:00" level=debug msg="Error looking for integration executables in folder. Trying another folder, if any." component=integrations.Executables error="open C:\\Program Files\\New Relic\\newrelic-infra\\bundled-plugins: The system cannot find the file specified." folder="C:\\Program Files\\New Relic\\newrelic-infra\\bundled-plugins" forName=mssql-server
time="2022-02-21T15:52:13+02:00" level=debug msg="Error looking for integration executables in folder. Trying another folder, if any." component=integrations.Executables error="open C:\\Program Files\\New Relic\\newrelic-infra\\bundled-plugins\\bin: The system cannot find the path specified." folder="C:\\Program Files\\New Relic\\newrelic-infra\\bundled-plugins\\bin" forName=mssql-server
time="2022-02-21T15:52:13+02:00" level=debug msg="Error looking for integration executables in folder. Trying another folder, if any." component=integrations.Executables error="open C:\\Program Files\\New Relic\\newrelic-infra\\plugins: The system cannot find the file specified." folder="C:\\Program Files\\New Relic\\newrelic-infra\\plugins" forName=mssql-server
time="2022-02-21T15:52:13+02:00" level=debug msg="Error looking for integration executables in folder. Trying another folder, if any." component=integrations.Executables error="open C:\\Program Files\\New Relic\\newrelic-infra\\plugins\\bin: The system cannot find the path specified." folder="C:\\Program Files\\New Relic\\newrelic-infra\\plugins\\bin" forName=mssql-server
time="2022-02-21T15:52:13+02:00" level=warning msg="can't instantiate integrations from file" component=integrations.Manager error="can't instantiate integration: can't find an executable given the name: mssql-server" file="C:\\Program Files\\New Relic\\newrelic-infra\\integrations.d\\mssql-config.yml"

[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # 
- Download the MSSQL integration (https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration/). 
- Run the MSI installer. 
- Create a mssql-config file with integration -name nri-mssql
integrations:
  - name: nri-mssql
    env:
      METRICS: true
      HOSTNAME: localhost
      USERNAME: newrelic
      PASSWORD: ""
      # Both port and instance can be omitted to use a default port of 1433
      PORT: 1433
      CUSTOM_METRICS_QUERY: >-
        SELECT 'count_entries' as metric_name, 
          count(*) AS metric_value, 
          'gauge' as metric_type
          FROM  MyTable
    labels:
      env: production
      role: mssql
      customer: MyCustomer

- Start the infrastructure agent service 
- Check the logs for the error 
level=debug msg="Integration name not found. Trying another folder, if any." component=integrations.Executables folder="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations" forName=mssql-server

- Stop the infrastructure agent
- Then copy the newrelic-infra\newrelic-integrations\bin\nri-mssql.exe file to the newrelic-infra\custom-integrations\bin directory
- Start the infra agent.
- Check in the logs that the error has gone away. 
- 
[TIP]:  # https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration/

## Your Environment
[TIP]:  # This issue was encountered on Windows 10 Pro 10.0.18362 and Windows 2019 

## Additional context
[TIP]:  # The nri-mssql executable had to be copied to the custom-integration\bin directory manually to get it to work.

**Comment by carlossscastro** [comment]
Hi @sajidinsaf,

Thanks for reaching out
The nri-mssql.exe file is copied at installation time to `\Program Files\New Relic\newrelic-infra\newrelic-integrations\bin` and it should run from there.
When setting up your `mssql-config.yml` file, did you by any chance change the name of the integration? it should always be `nri-mssql` as the name of the executable.

```
integrations:
- name: nri-mssql
  env:
    HOSTNAME: 
    .....

```

Looking at the logs it seems the integration was looking for a different binary name as seen on the `forName`:

The system cannot find the file specified." folder="C:\Program Files\New Relic\newrelic-infra\custom-integrations\bin" forName=mssql-server

Regards,

**Comment by sajidinsaf** [comment]
[Hi @carlossscastro ,

Thank you for looking into the issue and spotting this. I inadvertently copied the logs from the version where the client was using the incorrect executable name. The following log lines are from the version where the correct exe name was used. 

time="2022-02-24T13:22:14+02:00" level=debug msg="Integration name not found. Trying another folder, if any." component=integrations.Executables folder="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations" forName=nri-mssql
time="2022-02-24T13:22:14+02:00" level=debug msg="Updated runner." cfgPath="C:\\Program Files\\New Relic\\newrelic-infra\\integrations.d\\mssql-config.yml" component=integrations.runner.Runner

[newrelic-infra 18.33.27.log.zip](https://github.com/newrelic/nri-mssql/files/8137827/newrelic-infra.18.33.27.log.zip)

When we manually copied nri-mssql.exe to custom-integrations\bin we got the log message below:
time="2022-02-24T13:22:21+02:00" level=debug msg="Running command." command="C:\\Program Files\\New Relic\\newrelic-infra\\custom-integrations\\bin\\nri-mssql.exe" component=integrations.Executor 

I am attaching the entire log file for your perusal. Please note there were other issues with the yaml file which we resolved and were eventually successful in collecting the custom metrics we [needed.](url)

](url)

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
