### ISSUE TITLE
Docs about supported OSs for this integration are outdated 

### ISSUE THREAD

**Issue by kang-makes** [newrelic/nri-mssql#90]
## Description
We have an issue with the docs for this integration regarding the supported OSs. [Our docs](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration/#supported-os) only list Windows as supported Os while we are releasing for all the OSs and architectures:

![Screenshot 2022-07-11 at 12 57 55](https://user-images.githubusercontent.com/53659978/178249768-ebb73d94-3372-4d90-a096-cdb205a0e9e5.png)

## Expected Behavior
We should update the docs to remove that part as there are no particularities on the OSs that we support for this integration, we simply support the same OSs that the agent support.

**Comment by mangulonr** [comment]
PR - https://github.com/newrelic/docs-website/pull/8592

**Comment by sigilioso** [comment]
Closing this because @mangulonr docs PR was already merged and published, thanks!
